# Generated by Django 4.2.5 on 2023-09-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tarefa_dia_alter_tarefa_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(choices=[('pr', 'Profissional'), ('pe', 'Pessoal')], max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.categoria'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('p', 'Pendente'), ('c', 'Concluída')], default='pendente', max_length=10),
        ),
    ]
